remove the callbacks onColumnRemove onColumnRename onCardRemove
lourenci/react-kanban pull request #363
Opened 2020-06-02 05:45 UTC by deepakmountble

* [ ] Documentation
Remove the need of the callbacks #140

2020-06-03 23:28 UTC, matheus-poli requested changes

2020-06-03 23:28 UTC, MatheusPoliCamilo commented on src/components/Board/index.js
> -  onCardRemove,
The onColumnRemove, onColumnRename and onCardRemove callbacks are still needed, they just shouldn't be mandatory as they are currently, forcing us to specify them even if we don't need to do anything after these actions.

I made a [sandbox](https://codesandbox.io/s/issue-140-react-kanban-23chs) to better demonstrate the problem to you.

2020-06-05 12:31 UTC, deepakmountble commented on src/components/Board/index.js
> +    { onCardRemove && onCardRemove(
@MatheusPoliCamilo  hey can you help me why is this error both are 2 different codes.

2020-06-17 00:13 UTC, MatheusPoliCamilo commented on src/components/Board/index.js
> +    { onCardRemove && onCardRemove(
Hey @deepakmountble, sorry for keep you waiting! I've made some [contributions](https://github.com/deepakmountble/react-kanban/pull/1) that maybe fix this problem to you, can you see that everything is right and accept them? Thanks!!!

2020-06-17 00:15 UTC, matheus-poli requested changes
You need to create Jest specs for the new behavior that you added to the project. If you need any help, please call me and I will try to help you!

2020-06-20 15:23 UTC, lourenci requested changes
Sorry for the late on this.

I think we have another candidate for an optional callback. Can you take a look at the `onColumnNew`?

As for the specs, I think you can use a similar existing context to complement with yours. E.g.:
```
describe('about the column renaming', () => {
  describe('when the component use the default header template', () => {
    describe('when the component receives the "allowRenameColumn" prop', () => {
      describe('when the component does not receive the "onColumnNew" prop', () => {
          it('does not call the "onColumnRename" callback when the user renames a lane', () => {

```
I've plans to refactor those contexts, don't be afraid to add your behavior. The priority here is they be tested.

Please, update the docs to make those callbacks optionals.

I write down some annotations that should ditch codeclimate issues.

Thank you for your contribution.

2021-09-09 19:19 UTC, Sabrinovsky commented
Hey @deepakmountble still working on this PR? 
Looks like theres some requestest changes not applied yet, and also some problems with the linter.
If you need something let us know.

2022-10-08 12:21 UTC, closed without merging